### PR TITLE
Add functions to show RGB as leaflet layers

### PR DESCRIPTION
**Pull request by ranghetti**
I was looking for a way to add RGB images to a leaflet object, in a way similar to functions `addRasterRGB()` and `addStarsRGB()`. Since I did not find any solution, I wrote the two functions `addRasterRGB()` and `addStarsRGB()`, derived from your `viewRGB()` methods.
Thank you for writing and providing this useful package,
Luigi

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thank you very much for this PR! 

You couldn't possibly have known this but I am currently in the progress of converting mapview into a pure leaflet wrapper package. All functions that extend leaflet are now moved to package leafem which is also hosted here on r-spatial. 

Therefore, could I ask you to provide the PR there? I would then re-write viewRGB to use those functions (or if you feel productive enough you could also provide a PR for this here). 

Mapview has grown out of hand and is quite hard to maintain, hence the breakup into several smaller packages with a clearer focus.

One thing we should watch closely is the dependencies that these functions may introduce in leafem and which of the helper functions from mapview are needed to implement add*RGB functions in leafem. But I'm sure we can find a good way to handle these potential issues.

**Comment by ranghetti** [comment]
I am trying to move these functions to `leafem`: helper functions seem not to be a big problem, while the two "heavy" dependencies are `addRasterImage` and `addStarsImage`. Is it a good idea to move also these two functions to `leafem`?

**Comment by tim-salabim** [comment]
`addRasterImage` is from package leaflet so no need to be moved. `addStarsImage` would also need to be moved to leafem, yes.

**Comment by ranghetti** [comment]
I made the edits in #230 and [request 1 on leafem](https://github.com/r-spatial/leafem/pull/1), so I close this one.

**Pull request closed without merging**
