### PR TITLE
Travis: Use tic, automatic pkgdown deployment and apt sources

### PR DESCRIPTION
**Pull request by pat-s**
#### Changes

* On successful build, `pkgdown` site is automatically deployed. You may need to switch the site serving to `gh-pages`
* `tic` is a CI-agnostic way to specify Travis stages. It also uses the enhanced `rcmdcheck::rcmdcheck()`. One advantages is an enhanced error log.
* Installation of `libgdal` etc. via the `addons` plugin of Travis

There are still warnings and errors in the build but I'll leave these to you :smile:

### CODE REVIEW

**Comment by pat-s** [comment]
@tim-salabim build passes in 6 mins. What are your thoughts on this?

**Comment by tim-salabim** [comment]
I really don't know travis that well, so let's try this. May need further assistance down the line...

**Comment by pat-s** [comment]
Happy to help! 

To get the deployment working, you need to run `travis::use_travis_deploy()` once and change your Github pages branch under "Settings" to `gh-pages` :)

**Comment by pat-s** [comment]
Ah its easy - you do not have the `gh-pages` branch in your repo, simply create it :)

I also need to change the deployment branch to `develop` as its still set to `master`. PR soon.

**Comment by tim-salabim** [comment]
`gh-pages` branch created

**Pull request merged**
