### PR TITLE
allow rendering and downsampling of strs proxy raster

### PR DESCRIPTION
**Pull request by lbusett**
Cleaner PR - sorry for the mess!

### CODE REVIEW

**Comment by tim-salabim** [comment]
Yep, looks cleaner. No worries, I really appreciate your help!

**Comment by tim-salabim** [comment]
Heads up, I just completely messed up your PR. I will try to reimplement soon. Sorry.

**Comment by lbusett** [comment]
> Heads up, I just completely messed up your PR. I will try to reimplement soon. Sorry.

Let me know if i can help!

**Comment by tim-salabim** [comment]
Should work again now. Note that it will affect both new (`leafem::addGeoRaster` - used if leafem >= 0.1.3.) and standard rendering (`leafem::addStarsImage`). Also, consider this a hotfix (i.e. I might break things again :-|), as I am planning to completely separate the two and add an option to let the user decide which to use. I think that for small raster data sets the standard png rendering is fine and has some advantages when e.g. used with rmarkdown or in shiny.

**Pull request merged**
