### PR TITLE
Add text labels to 'mapview' object

### PR DESCRIPTION
**Pull request by fdetsch**
Here's a little something I came up with in response to [this post](https://gis.stackexchange.com/questions/274288/r-add-labels-to-spatial-grid-in-leaflet/274421?noredirect=1#comment437557_274421) on GIS StackExchange. In brief, the question was about how to draw permanent text labels on a **leaflet** map, among others. Same issue [here](https://stackoverflow.com/questions/31745525/leaflet-with-r-add-text-labels). 

I think that such functionality would be nice to have in a **mapview** generic way, that means without being explicitly required to rewrite the whole `map@map %>% addLabelOnlyMarkers(...)` part over and over again. Therefore, I'd be glad if you could simply rebuild the package, have a look at the Examples section in `?addLabels` &ndash; you'll probably get the point... &ndash; and tell me what you think about it. 

Some issues that still need to be addressed here, though: 

+ I think it would be nice to add labels via `%>%` pipelines (ie. the **leaflet** way) or `+` (ie. the **mapview** way), for example something like `mapview(m1) + addLabels(zcol = ...)`. What I mean is an approch that does not require an explicit specification of 'map' in the `addLabels()` environment. In addition, a 'zcol' argument could be advantageous that lets the user directly address a certain column in the dataset upon which the 'mapview' object has been built in the first place. Do you think this is possible / worth the effort? I know little about these kinds of things, and in the end @tim-salabim, it's your baby ;-)
+ `addLabels()` does not work with 'Raster*' input, yet.

Cheers, 
Florian

### CODE REVIEW

**Comment by gisma** [comment]
From an alldays user point of view  I totally agreed with  flo's points....

**Comment by tim-salabim** [comment]
Thanks @fdetsch for this PR! I agree that this is useful. Just a few points (before work):
- renamed the function to addStaticLabels (cause that's what it does).
- for points and polygons we can use st_centroid for placement, for lines we now take the last coordinates pair
- we need to find a smart way of combining a set of minimal options and potentially user supplied options
- we need to agree whether to bind the labels to the data layer or create its group for turning them on/off
- in general all `add*` functions should be compatible with leaflet and as such should not expect a mapview object. 
- more on the piping vs +ing later

Thoughts?

**Comment by fdetsch** [comment]
(You should really use numbers instead of bullets to make the whole referencing stuff a little easier for me ;-))

1. Agreed.
2. Clearly, this is owing to my lack in **sf** working practice (I only knew about `rgeos::gCentroid()` before); those geometric unary operations should easily do the job!
3. `garnishMap()` is your creation &ndash; you know best how to deal with this. But I agree, we should definitely choose minimal options that match up with the needs of typical **mapview** users (right, @gisma? :-))
4. Your decision, I reckon that I'm not deep enough into **mapview** to significantly contribute to a decision.
5. Yeah, well... I like **mapview** and keeping things simple! Nonetheless, you got a point as regards all those `add*` functions.
6. Sounds reasonable. 

I know, not that much of input, but you're the expert here. I'm satisfied with having contributed the idea to include such functionality and a tiny code snippet :-)

**Comment by tim-salabim** [comment]
Edited!

3. I hope to find some more time to work on this tonight. 
4. In my opinion, binding them to the respective layer would be the best.
5. This is a nice data-driven function (very mapview). So it would be nice to have it as a general leaflet add-on. I will implement a step to use the mapview@object[[1]] if map is a mapview object and no data is supplied.

Regarding mapview simplicity, this is actually the hardest bit about the package. On the one hand, as everyone seems to agree, we should try to avoid overloading mapview with too many arguments, on the other hand we would like it to be flexible at the same time. It is hard for me to judge where to draw the line between "yes, that should be implemented for mapview" and "well, this is beyond mapview scope so better implement yourself using leaflet". We could, for future version adopt the approach that lattice/leaflet and others use to provide an `options = mapviewOptions()` argument where we bundle all not-so-often needed arguments to provide a cleaner API. This is desirable, but also a lot of work (and will break things obviously - though I consider that less of an issue regarding the scopr of mapview). Anyway, this should be discussed elsewhere (in its own issue).

**Comment by tim-salabim** [comment]
Ok, so now we have a more sophisticated version. 
The only thing not addressed yet is implementation in mapview. But the following should give an impression of current status:

```r
library(mapview)
library(leaflet)

## mapview objects (labels bound to layer by default)
m = mapview(franconia)

m %>% addStaticLabels()
m %>% addStaticLabels(textsize = "20px")
m %>% addStaticLabels(label = franconia$NAME_ASCI)

addStaticLabels(mapview(atlStorms2005), label = atlStorms2005$Name)

## leaflet objects
leaflet() %>%
  addProviderTiles("OpenStreetMap") %>%
  addPolygons(data = franconia, group = "fran") %>%
  addStaticLabels(data = franconia, group = "fran_labs") %>%
  addLayersControl(overlayGroups = c("fran", "fran_labs"))

leaflet() %>%
  addProviderTiles("OpenStreetMap") %>%
  addPolygons(data = franconia, group = "fran") %>%
  addStaticLabels(data = franconia, group = "fran") %>%
  addLayersControl(overlayGroups = c("fran"))
```
mapview implementation to follow...

**Comment by tim-salabim** [comment]
@fdetsch what do you think should addStaticLabels do for raster layers?

**Comment by lbusett** [comment]
Hi, 

  just wanted to signal that the functionality does not seem to work anymore. Running the above examples (or the ones in the documentation of the function) does not seem to show any labels:

```
library(mapview)
library(leaflet)

## mapview objects (labels bound to layer by default)
m = mapview(franconia)
m %>% addStaticLabels(label = franconia$NAME_ASCI)`
```

image

Additionally, trying to use the function to render labels in a shiny app with something like: 

````
output$pcolt_map <- renderMapview({
                     m <- mapview::mapView(data,
                                           zcol = "coltura") %>%
                       mapview::addStaticLabels(
                                                data = data,
                                                label = data$$id_geom,
                                                labelOptions = lopt)
                     m
                   })
```

gives the following error: 

> Error in methods::slot: no slot of name "map" for this object of class "leaflet"

(don't know if it is related, or I am just doing something wrong in this case)

Working with leaflet 2.0 and mapview 2.4.0

**Comment by tim-salabim** [comment]
@lbusett thanks for the report. I will look into it. I had also noticed that leaflet 2.0.0 broke staticLabels.

**Pull request merged**
