### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by pat-s**
Let'see what happens.

### CODE REVIEW

**Comment by pat-s** [comment]
Now it worked, do we even need `liblwgeom-dev` then?

**Comment by tim-salabim** [comment]
I don't think so as package `lwgeom` now ships its own `liblwgeom` if I understand @edzer correctly.

**Comment by tim-salabim** [comment]
This can be merged right?

**Comment by pat-s** [comment]
Yes.

**Comment by tim-salabim** [comment]
Thanks Patrick! Seems to work now. Much appreciated!

**Comment by tim-salabim** [comment]
Hi @pat-s, any idea what is happening here https://travis-ci.org/r-spatial/mapview/jobs/538875309? I updated the `tic.R` to reflect what you PR'd into sf recently, but that does not seem to solve the problem for mapview...?

**Comment by pat-s** [comment]
Not yet sure what the root is here - Let's see if the error persists in the next builds. Sorry for the trouble!

**Comment by tim-salabim** [comment]
Thanks, I'll be patient :-)

**Pull request merged**
