### PR TITLE
Update viewRGB doc and stars since it's supported

### PR DESCRIPTION
**Pull request by dickoa**

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thanks!

**Comment by tim-salabim** [comment]
Sorry reverted the PR since it was merged into master. This is a bit of a mess here currently. I will integrate this manually, sorry.

**Comment by dickoa** [comment]
It's perfect, I hesitated to tell you directly instead of the PR in order to simplify your workflow!
Thanks for this amazing package and all the goodies that keep coming!

**Comment by tim-salabim** [comment]
PRs are much appreciated! I just need to get rid of the `develop` branch. It confuses too many people. I once thought it's be nice to have a clean release branch (master) and a dev branch (develop) but turns out CRAN is the perfect release branch, so there's no need for the develop branch really. Will get rid of it soon I hope...

**Comment by edzer** [comment]
Merge it into master?

**Comment by tim-salabim** [comment]
I will. But I need some quiet time to do this, I fear there's a whole lot of stuff that will break (including a lot of SO answers) :-(

**Pull request merged**
