### PR TITLE
fix tic

### PR DESCRIPTION
**Pull request by pat-s**
@krlmlr did a lot of work lately and fixed most of the issues. I cannot fully guarantee that this version is fully stable now but we are close to a CRAN release.

I also tidied the DESCRIPTION using usethis::use_tidy_description().

Build is passing even though there are issues in the `covr` call.

### CODE REVIEW

**Comment by tim-salabim** [comment]
Nearly... Odd error "there is no package called mapview"
https://travis-ci.org/r-spatial/mapview/jobs/426535094#L3909

**Comment by pat-s** [comment]
@tim-salabim fixed

**Comment by tim-salabim** [comment]
Yes, I got the mail. Do you know where the covr call disappeared? It seems it doesn't update the coverage anymore...

**Comment by pat-s** [comment]
It got executed but errored: https://travis-ci.org/r-spatial/mapview/jobs/426868191#L3442

Looks like `covr` related?

**Pull request merged**
