### PR TITLE
Remove DrawTools and EasyButtons in mapshot

### PR DESCRIPTION
**Pull request by trafficonese**
Extends `remove_controls` with 2 additional options `drawToolbar` and `easyButton`.

I also did a bit of cleanup, but I'm not sure if that was a good idea, since the code got me a bit confused, as some parts are running twice: 

-  `removeMapJunk`  in https://github.com/r-spatial/mapview/blob/c1d5a66e421110fa601994b42c1dbd9728a6978e/R/mapshot.R#L92 and
https://github.com/r-spatial/mapview/blob/c1d5a66e421110fa601994b42c1dbd9728a6978e/R/mapshot.R#L130

- `htmlwidgets::saveWidget` in https://github.com/r-spatial/mapview/blob/c1d5a66e421110fa601994b42c1dbd9728a6978e/R/mapshot.R#L120 and
https://github.com/r-spatial/mapview/blob/c1d5a66e421110fa601994b42c1dbd9728a6978e/R/mapshot.R#L133

Also the `url_tmp_files` variable seems to be unnecessary, so I removed it.

I might have missed something, which makes those duplicated parts or `url_tmp_files` necessary. I only tested with exporting to file, which works fine.

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thanks! This makes total sense. 

> Also the url_tmp_files variable seems to be unnecessary, so I removed it.

No, we need this. This makes sure that not only the temporary html is removed but also the folder that contains all the html deps. 

As for the duplicated calls, this stems from the fact that we handle the two scenarios (url specified vs. url not specified) in two different code blocks. I am sure there's a better way to go about this, so how about you leave those as they are and only add the new `remove_controls` and I will then clean that code as best I can. I remember I included all of this to make sure we save the html with the controls but the png without them in case both `url` & `file` are provided.

**Comment by trafficonese** [comment]
Ah, I was sure there was something behind it. 

I just undid those changes. My problem is that `htmlwidgets::saveWidget` is already a fairly lengthy process and I want to prevent it from having to be run twice.

I am only interested in the .png file and with the previous changes everything worked fine. The temporary html and the folder with deps were removed.

**Comment by tim-salabim** [comment]
Thanks! I'll take a look now

**Comment by tim-salabim** [comment]
The above commit now has much cleaner code (in my opinion anyway) and as far as I can see does not call anything twice if not necessary. If `url` and `file` are provided and `remove_controls` is not `NULL` then we need to call `saveWidget` twice, once with all the map elements and then without the ones specified in `remove_controls` to take the `webshot`.

I also exported `removeMapJunk` as I think it might be of use for other people too, also for blogposts or thelike...

**Pull request merged**
