### PR TITLE
Travis: Deploy pkgdown only on r-release and develop branch

### PR DESCRIPTION
**Pull request by pat-s**

### CODE REVIEW

**Comment by tim-salabim** [comment]
This one failed... See https://travis-ci.org/r-spatial/mapview/jobs/371077832

**Comment by pat-s** [comment]
I know, I wrote something in the r-spatial slack channel for you about it :)

**Comment by edzer** [comment]
You used to have `warnings_are_errors: false`, but this seems now to be `true`. It's not a bad idea to address these warnings, you need to do so anyway, but as a quick fix you could set it back to `false`.

**Comment by pat-s** [comment]
@edzer Its set to `FALSE`:

https://github.com/r-spatial/mapview/blob/2bb2dff15fa3624d639d118401355372d23bfd82/tic.R#L1

There are issues with the `pkgdown` deployment, that's why the `release` build is currently failing. 
R CMD check is fine.

**Comment by tim-salabim** [comment]
If `coords2Lines` is the culprit, as you suggest on slack, then I can remove it, as we don't need it anymore... This is a rudimentary function when everything was based on sp. Still, I don't undersatnd why this should be the problem...

**Comment by pat-s** [comment]
I would more believe the issue that Travis throws  in https://travis-ci.org/pat-s/mapview/jobs/371051663

```r
Reading 'vignettes/articles/mapview_01-basics.Rmd'
Error: recursive indexing failed at level 2
```

Its thrown by `pkgdown`  itself, maybe because you are using an `html_document()` instead of an `html_vignette()`.

**Comment by tim-salabim** [comment]
Good catch, the vignette fails in this line... 
```r
mapview(breweries, zcol = c("brewery", "village", "founded"))
```
Will debug

**Comment by pat-s** [comment]
The error from the last build:

```
Reading 'vignettes/articles/mapview_06-add.Rmd'
Error: there is no package called 'magick'
```

is solved by adding `add_code_step(if (length(find.package("magick", quiet = TRUE)) == 0) install.packages("magick")) %>%` in `tic.R`:

```r
get_stage("install") %>%
  add_code_step(if (length(find.package("magick", quiet = TRUE)) == 0) install.packages("magick")) %>%
  # install lwgeom with its own library since linking again postgis source install fails sometimes
  add_code_step(install.packages("lwgeom", configure.args="--without-liblwgeom")) %>% # normal installation does not work
  add_code_step(remotes::install_github("r-spatial/stars"))
```

**Comment by pat-s** [comment]
Sure, just an example how to add missing R packages that Travis complains about. If any others are missing, you can simply add more lines. They will be added to the cache after they have been installed once.

**Comment by tim-salabim** [comment]
Sweet! Works now that vignettes are fixed. Thanks for this @pat-s !

**Pull request merged**
